config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"

  get "home/about" => "homes#about", as: "about"

  devise_for :users

  resources :books, only: [:index, :show, :create, :edit, :destroy, :update]
  resources :users, only: [:show, :edit, :index, :update]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, { uniqueness: true, length: { in: 2..20 } }
  validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image

  has_many :books, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "You have created book successfully."
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :image, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user_info.html.erb
<h2>User info</h2>
<%= image_tag current_user.get_profile_image(63,63) %>
<table class="table">
  <tbody>
   <tr></tr>
   <tr>
     <th>name</th>
     <th><%= current_user.name %></th>
   </tr>
   <tr>
     <th>introduction</th>
     <th><%= current_user.introduction %></th>
   </tr>
  </tbody>
</table>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <h3 class="text-danger"><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="form-group">
      <%= form_with(model:@book,local:true) do |f| %>
        <label for="book_title">Title</label>
        <%= f.text_field:title,autofocus:true,id:"book_title",class:"form-control mb-3" %>
        <label for="book_opinion">Opinion</label>
        <%= f.text_area:body,id:"book_body",class:"form-control mb-3" %>
        <%= f.submit "Update Book",class:"btn btn-success" %>
      <% end %>
      </div>
      <%= link_to "Show",book_path(@book.id) %> | <%= link_to "Back",books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">

  <% if @book.errors.any? %>
    <h3 class="text-danger"><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
    </ul>
  <% end %>

 <div class="row">
   <div class="col-md-3">
     <%= render "user_info" %>
     <div class="row">
      <%= link_to(edit_user_path(current_user.id),class:"btn btn-outline-secondary btn-block") do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
     </div>
     <h2 class="mt-3">New book</h2>
     <%= form_with(model:@book,local:true) do |f| %>
     <div class="form-group">
       <label for="book_title">Title</label>
       <%= f.text_field:title,class:"form-control book_title" %>
     </div>
     <div class="form-group">
       <label for="book_opinion">Opinion</label>
       <%= f.text_area:body,class:"form-control book_opinion" %>
     </div>
     <%= f.submit 'Create Book',class:"btn btn-success" %>
     <% end %>
   </div>
   <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table table-hover table-inverse">
       <thead>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
       </thead>
       <tbody>
         <% @books.each do |book| %>
         <tr>
           <td>
             <%= link_to user_path(book.user.id) do %>
               <%= image_tag book.user.get_profile_image(40,40) %>
             <% end %>
             </td>
           <td><%= link_to book.title,book_path(book.id) %></td>
           <td><%= book.body %></td>
         </tr>
         <% end %>
       </tbody>
     </table>
   </div>
 </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class="row">
   <div class="col-md-3">
     <h2>User info</h2>
     <%= image_tag @book.user.get_profile_image(63,63) %>
     <table class="table">
       <tbody>
         <tr></tr>
         <tr>
           <th>name</th>
           <th><%= @book.user.name %></th>
         </tr>
         <tr>
           <th>introduction</th>
           <th><%= @book.user.introduction %></th>
         </tr>
       </tbody>
     </table>
     <div class="row">
      <%= link_to(edit_user_path(@book.user.id),class:"btn btn-outline-secondary btn-block") do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
     </div>
     <h2 class="mt-3">New book</h2>
     <%= form_with(model:@book_new,local:true) do |f| %>
     <div class="form-group">
       <label for="book_title">Title</label>
       <%= f.text_field:title,class:"form-control book_title" %>
     </div>
     <div class="form-group">
       <label for="book_opinion">Opinion</label>
       <%= f.text_area:body,class:"form-control book_opinion" %>
     </div>
     <%= f.submit 'Create Book',class:"btn btn-success" %>
     <% end %>
   </div>
   <div class="col-md-8 offset-md-1">
     <h2>Book detail</h2>
     <table class="table">
       <tbody>
         <tr>
           <td>
             <%= link_to book_path(@book.id) do %>
               <%= image_tag @book.user.get_profile_image(40,40) %>
             <% end %>
             <br><%= link_to @book.user.name,user_path(@book.user.id) %>
           </td>
           <td><%= link_to @book.title,book_path(@book.id) %></td>
           <td><%= @book.body %></td>
           <% if @book.user.id == current_user.id %>
           <td><%= link_to "Edit",edit_book_path(@book.id),class:"btn btn-sm btn-success" %></td>
           <td><%= link_to "Destroy",book_path(@book),method: :delete,class:"btn btn-sm btn-danger",data:{confirm:"本当に消しますか？"} %></td>
           <% end %>
         </tr>
       </tbody>
     </table>
   </div>
 </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 aol-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchage your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "ゲストログイン（閲覧用）",users_guest_sign_in_path, class:"btn btn-secondary btn-sm btn-block mb-3 sign_in",method: :post %>
        </div>
        <div class="row">
          <%= link_to "Log in",new_user_session_path,class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up",new_user_registration_path,class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"
                  data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
                  aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <% if user_signed_in? %>
                  <%= link_to(user_path(current_user.id),class:"nav-link text-light") do %>
                  <i class="fas fa-home"></i> Home
                  <% end %>
                <% else %>
                  <%= link_to(root_path,class:"nav-link text-light") do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                <% end %>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to(users_path,class:"nav-link text-light") do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to(books_path,class:"nav-link text-light") do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to(destroy_user_session_path,method: :delete,class:"nav-link text-light") do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to(about_path,class:"nav-link text-light") do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to(new_user_registration_path,class:"nav-link text-light") do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to(new_user_session_path,class:"nav-link text-light") do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>

      <% flash.each do |key,value| %>
       <%= content_tag :div,value,class:"#{key} text-success" %>
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto"><p>CopyRight Infratop.inc</p></div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <h3 class="text-danger"><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li class="text-danger"><%= message %></li>
          <% end %>
          </ul>
      <% end %>

      <div class="form-group">
      <%= form_with(model:@user,local:true) do |f| %>
        <label for="user_name">Name</label>
        <%= f.text_field:name,autofocus:true,id:"user_name",class:"form-control mb-3" %>
        <label for="user_image">Image</label><br>
        <%= f.file_field:profile_image,accept:"image/*",class:"mb-3" %><br>
        <label for="user_introduction">Introduction</label>
        <%= f.text_area:introduction,id:"user_introduction",class:"form-control mb-3" %>
        <%= f.submit "Update User",class:"btn btn-secondary" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class="row">
   <div class="col-md-3">
     <%= render "books/user_info" %>
     <div class="row">
      <%= link_to(edit_user_path(current_user.id),class:"btn btn-outline-secondary btn-block") do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
     </div>
     <h2 class="mt-3">New book</h2>
     <%= form_with(model:@book,local:true) do |f| %>
     <div class="form-group">
       <label for="book_title">Title</label>
       <%= f.text_field:title,class:"form-control book_title" %>
     </div>
     <div class="form-group">
       <label for="book_opinion">Opinion</label>
       <%= f.text_area:body,class:"form-control book_opinion" %>
     </div>
     <%= f.submit 'Create Book',class:"btn btn-success" %>
     <% end %>
   </div>
   <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
     <table class="table">
       <thead>
         <th>image</th>
         <th>name</th>
         <th colspan="3"></th>
       </thead>
       <tbody>
         <% @users.each do |user| %>
         <tr>
           <td>
             <%= image_tag user.get_profile_image(40,40) %>
           </td>
           <td><%= user.name %></td>
           <td><%= link_to "Show",user_path(user.id) %></td>
         </tr>
         <% end %>
       </tbody>
     </table>
   </div>
 </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class="row">
   <div class="col-md-3">
     <h2>User info</h2>
     <%= image_tag @user.get_profile_image(63,63) %>
     <table class="table">
       <tbody>
         <tr></tr>
         <tr>
           <th>name</th>
           <th><%= @user.name %></th>
         </tr>
         <tr>
           <th>introduction</th>
           <th><%= @user.introduction %></th>
         </tr>
       </tbody>
     </table>
     <% if @user.name != "guestuser" %>
       <div class="row">
        <%= link_to(edit_user_path(@user.id),class:"btn btn-outline-secondary btn-block") do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
       </div>
     <% end %>
     <h2 class="mt-3">New book</h2>
     <%= form_with(model:@book,local:true) do |f| %>
     <div class="form-group">
       <label for="book_title">Title</label>
       <%= f.text_field:title,class:"form-control book_title" %>
     </div>
     <div class="form-group">
       <label for="book_opinion">Opinion</label>
       <%= f.text_area:body,class:"form-control book_opinion" %>
     </div>
     <%= f.submit 'Create Book',class:"btn btn-success" %>
     <% end %>
   </div>
   <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table table-hover table-inverse">
       <thead>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
       </thead>
       <tbody>
         <% @books.each do |book| %>
         <tr>
           <td>
             <%= link_to user_path(book.user.id) do %>
               <%= image_tag book.user.get_profile_image(40,40) %>
             <% end %>
             </td>
           <td><%= link_to book.title,book_path(book.id) %></td>
           <td><%= book.body %></td>
         </tr>
         <% end %>
       </tbody>
     </table>
   </div>
 </div>
</div>